on: push
name: Publish
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1

    - run: export NETLIFY_AUTH_TOKEN="${{ secrets.NETLIFY_AUTH_TOKEN }}"
    - run: wget https://github.com/gohugoio/hugo/releases/download/v0.58.2/hugo_0.58.2_Linux-64bit.deb
    - run: sudo dpkg -i hugo_0.58.2_Linux-64bit.deb
    - run: sudo apt-get install -f
    - run: npm install -g postcss-cli
    - run: npm install netlify-cli -g
    - run: npm install --prefix themes/minimalist
    - run: hugo
    - run: netlify deploy --prod --auth "${{ secrets.NETLIFY_AUTH_TOKEN }}" --site "${{ secrets.NETLIFY_SITE_ID }}" --dir "public"
