on: push
name: Publish
jobs:
  linux-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1

    - run: export NETLIFY_AUTH_TOKEN="${{ secrets.NETLIFY_AUTH_TOKEN }}"
    - run: sudo apt-get install hugo
    - run: npm install -g postcss-cli
    - run: npm install netlify-cli -g
    - run: hugo
    - run: netlify deploy --prod
